name = "sMCRT"
version = "1.0.0"
license = "MIT"
author = "Lewis McMillan"
maintainer = "lewisfish92"
copyright = "2020 Lewis McMillan"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"

[dependencies]
toml-f.git = "https://github.com/toml-f/toml-f"
tev_bindings.git = "https://github.com/lewisfish/fortran_tev_bindings"

[build]
external-modules = "mpi_f08"
auto-executables = false
auto-tests = false
auto-examples = false

[executable]
name="sMCRT"
source-dir="src"
main="main.f90"

[[test]]
name="vector-test"
source-dir="test/vector"
main="main.f90"