name = "sMCRT"
version = "1.0.0"
license = "MIT"
author = "Lewis McMillan"
maintainer = "lewisfish92"
copyright = "2020 Lewis McMillan"

[dependencies]
toml-f.git = "https://github.com/toml-f/toml-f"
tev_bindings.git = "https://github.com/lewisfish/fortran_tev_bindings"

[library]
source-dir="src"

[build]
external-modules = "mpi_f08"
auto-executables = false
auto-tests = false
auto-examples = false

[[ executable ]]
name="sMCRT"
source-dir="src"
main="main.f90"