[source]
name = "point"
nphotons = 10000

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "scat_test"
tau = 10.0

[output]
fluence = "fluence.nrrd"
render = "geom_render.nrrd"

[simulation]
iseed = 123456789