[source]
name = "uniform"
nphotons = 1000000
direction = [0.0, 0.0, -1.0]
point1 = [-2.5, -2.5, -2.5]
point2 = [5.0, 0.0, 0.0]
point3 = [0.0, 5.0, 0.0]

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 5.0
ymax = 5.0
zmax = 5.0

[geometry]
geom_name = "blobby"

[output]
fluence = "blobby.nrrd"
render = "blobby.nrrd"
render_geom = true
render_size = 50

[simulation]
iseed = 123456789