[source]
name = "uniform"
nphotons = 10000000
direction = "-z"

[grid]
nxg = 200
nyg = 200
nzg = 400
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "jacques"

[output]
fluence = "fluence.nrrd"
render = "geom_render.nrrd"
render_geom = true

[simulation]
iseed = 123456789