[source]
name = "uniform"
nphotons = 1000000
direction = "-z"

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "logo"

[output]
fluence = "logo.nrrd"
render = "logo_render.nrrd"
render_geom = false

[simulation]
iseed = 123456789