[source]
name = "uniform"
nphotons = 1000000
point1=[-1.0, -1.0, 0.99999]
point2=[2.0, 0.0, 0.0]
point3=[0.0, 2.0, 0.0]
direction=[0.0, 0.0, -1.0]

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 1.0
ymax = 1.0
zmax = 1.0

[geometry]
geom_name = "neural"

[output]
fluence = "bunny.nrrd"
render = "bunny.nrrd"
render_geom = true
overwrite=true

[simulation]
iseed = 123456789
tev=true