[source]
name='uniform'
nphotons=1000000
direction="-z"
point1 = [-1.0, -1.0, 0.9999999]
point2 = [2.0, 0.0, 0.0]
point3 = [0.0, 2.0, 0.0]

[grid]
nxg=200
nyg=200
nzg=200
xmax=1.0
ymax=1.0
zmax=1.0

[geometry]
geom_name='sphere_scene'
num_spheres=40

[output]
fluence='sphere_scene_40.nrrd'
render_geom=false
overwrite=true

[simulation]
iseed=123456789
tev=false

