[source]
name = "uniform"
nphotons = 1000000
point1=[-0.16, -0.09, 0.129999]
point2=[0.32, 0.0, 0.0]
point3=[0.0, 0.18, 0.0]
direction=[0.0, 0.0, -1.0]

[grid]
nxg = 200
nyg = 200
nzg = 200
xmax = 0.16
ymax = 0.09
zmax = 0.13

[geometry]
geom_name = "vessels"

[output]
fluence = "vessels.nrrd"
render = "vessels_render.nrrd"
render_geom = false
overwrite=true

[simulation]
iseed = 123456789
tev=false