on: [push]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [9,10,11] # Version of GFortran we want to use.
        build: [fpm]
        include:
          - os: ubuntu-latest
            gcc_v: 10

    env:
      FC: gfortran-${{ matrix.gcc_v }}
      CC: gcc-${{ matrix.gcc_v }}
      CXX: g++-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O fpm https://github.com/fortran-lang/fpm/releases/download/current/fpm-linux-x86_64 

    - name: rename
      run: |
        sudo chmod +x fpm

    # - uses: fortran-lang/setup-fpm@v4
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install GCC compilers Linux
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-${GCC_V} g++-${GCC_V} gfortran-${GCC_V}
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/g++ g++ /usr/bin/g++-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install GCC compilers macOS
      if: contains( matrix.os, 'macos')
      run: |
          brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true
          brew link gcc@${GCC_V}

    - name: Build and compile
      if: ${{ contains(matrix.build, 'fpm') }}
      run: ./fpm @build

    - name: Test and compile
      if: ${{ contains(matrix.build, 'fpm') }}
      run: ./fpm @test

    - name: Run CodeCov
      run: |
        gcov ./build/gfortran_*/sMCRT/src*.gcda -r ./src/ -b
    
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1